/**
 * Outbound notifications queue — list pending SMS/WhatsApp/Email rows
 * generated by the appointment triggers, mark sent/skipped/retry.
 */
import { createServerFn } from "@tanstack/react-start";
import { requireSupabaseAuth } from "@/integrations/supabase/auth-middleware";
import { logAppEvent } from "./audit-log.server";
import { z } from "zod";

type Role = "admin" | "super_admin" | "reception" | "doctor" | "pharmacy";

async function getRoles(sb: any, userId: string): Promise<Role[]> {
  const { data } = await sb.from("user_roles").select("role").eq("user_id", userId);
  return (data ?? []).map((r: any) => r.role as Role);
}
function ensureStaff(roles: Role[]) {
  if (!roles.some((r) => (["admin", "super_admin", "reception"] as Role[]).includes(r)))
    throw new Error("ليست لديك الصلاحية.");
}

export type OutboundNotification = {
  id: string;
  channel: "in_app" | "sms" | "whatsapp" | "email";
  send_status: "pending" | "queued" | "sent" | "failed" | "skipped";
  recipient: string | null;
  title: string;
  body: string | null;
  kind: string;
  appointment_id: string | null;
  branch_id: string | null;
  created_at: string;
  sent_at: string | null;
  last_error: string | null;
  metadata: import("@/integrations/supabase/types").Json | null;
};

const ListInput = z
  .object({
    channel: z.enum(["sms", "whatsapp", "email", "in_app"]).nullable().optional(),
    status: z
      .enum(["pending", "queued", "sent", "failed", "skipped"])
      .nullable()
      .optional(),
    branchId: z.string().uuid().nullable().optional(),
    limit: z.number().int().min(1).max(500).optional(),
  })
  .default({});

export const listOutboundNotifications = createServerFn({ method: "POST" })
  .middleware([requireSupabaseAuth])
  .validator((d: unknown) => ListInput.parse(d))
  .handler(async ({ data, context }): Promise<OutboundNotification[]> => {
    const roles = await getRoles(context.supabase, context.userId);
    ensureStaff(roles);
    let q = context.supabase
      .from("notifications")
      .select(
        "id, channel, send_status, recipient, title, body, kind, appointment_id, branch_id, created_at, sent_at, last_error, metadata",
      )
      .order("created_at", { ascending: false })
      .limit(data.limit ?? 100);
    // Default: exclude in-app (they're delivered immediately)
    q = data.channel ? q.eq("channel", data.channel) : q.neq("channel", "in_app");
    if (data.status) q = q.eq("send_status", data.status);
    if (data.branchId) q = q.eq("branch_id", data.branchId);
    const { data: rows, error } = await q;
    if (error) throw new Error(error.message);
    return (rows ?? []) as unknown as OutboundNotification[];
  });

export const outboundNotificationStats = createServerFn({ method: "POST" })
  .middleware([requireSupabaseAuth])
  .validator((d) =>
    z.object({ branchId: z.string().uuid().nullable().optional() }).default({}).parse(d),
  )
  .handler(async ({ data, context }) => {
    const roles = await getRoles(context.supabase, context.userId);
    ensureStaff(roles);
    const channels = ["sms", "whatsapp", "email"] as const;
    const stats: Record<string, { pending: number; sent: number; failed: number }> = {};
    for (const c of channels) {
      const base = () => {
        let b = context.supabase
          .from("notifications")
          .select("id", { count: "exact", head: true })
          .eq("channel", c);
        if (data.branchId) b = b.eq("branch_id", data.branchId);
        return b;
      };
      const [p, s, f] = await Promise.all([
        base().eq("send_status", "pending"),
        base().eq("send_status", "sent"),
        base().eq("send_status", "failed"),
      ]);
      stats[c] = {
        pending: p.count ?? 0,
        sent: s.count ?? 0,
        failed: f.count ?? 0,
      };
    }
    return stats;
  });

export const setNotificationStatus = createServerFn({ method: "POST" })
  .middleware([requireSupabaseAuth])
  .validator((d) =>
    z
      .object({
        id: z.string().uuid(),
        status: z.enum(["pending", "queued", "sent", "failed", "skipped"]),
        error: z.string().max(1000).nullable().optional(),
      })
      .parse(d),
  )
  .handler(async ({ data, context }) => {
    const roles = await getRoles(context.supabase, context.userId);
    ensureStaff(roles);
    const patch: Record<string, unknown> = { send_status: data.status };
    if (data.status === "sent") patch.sent_at = new Date().toISOString();
    if (data.status === "failed" && data.error) patch.last_error = data.error;
    if (data.status === "pending") {
      patch.last_error = null;
      patch.sent_at = null;
    }
    const { error } = await context.supabase
      .from("notifications")
      .update(patch as never)
      .eq("id", data.id);
    if (error) throw new Error(error.message);
    return { ok: true };
  });

/* -------- Reminder delivery log (staff view) -------- */

export type ReminderDelivery = {
  id: string;
  appointment_id: string | null;
  kind: string;
  audience: "user" | "staff";
  channel: "in_app" | "web_push" | "sms" | "whatsapp" | "email";
  send_status: "pending" | "queued" | "sent" | "failed" | "skipped";
  title: string;
  body: string | null;
  created_at: string;
  sent_at: string | null;
  last_error: string | null;
  metadata: import("@/integrations/supabase/types").Json | null;
  appointment: {
    id: string;
    patient_name: string | null;
    patient_phone: string | null;
    appointment_date: string | null;
    appointment_time: string | null;
    status: string | null;
    branch_id: string | null;
  } | null;
};

const ListRemindersInput = z
  .object({
    appointmentId: z.string().uuid().nullable().optional(),
    channel: z.enum(["in_app", "web_push", "sms", "whatsapp", "email"]).nullable().optional(),
    audience: z.enum(["user", "staff"]).nullable().optional(),
    status: z.enum(["pending", "queued", "sent", "failed", "skipped"]).nullable().optional(),
    branchId: z.string().uuid().nullable().optional(),
    patientQuery: z.string().trim().max(120).nullable().optional(),
    dateFrom: z.string().regex(/^\d{4}-\d{2}-\d{2}$/).nullable().optional(),
    dateTo: z.string().regex(/^\d{4}-\d{2}-\d{2}$/).nullable().optional(),
    timeFrom: z.string().regex(/^\d{2}:\d{2}(:\d{2})?$/).nullable().optional(),
    timeTo: z.string().regex(/^\d{2}:\d{2}(:\d{2})?$/).nullable().optional(),
    limit: z.number().int().min(1).max(500).optional(),
  })
  .default({});

export const listReminderDeliveries = createServerFn({ method: "POST" })
  .middleware([requireSupabaseAuth])
  .validator((d: unknown) => ListRemindersInput.parse(d))
  .handler(async ({ data, context }): Promise<ReminderDelivery[]> => {
    const roles = await getRoles(context.supabase, context.userId);
    ensureStaff(roles);

    const hasApptFilter =
      !!data.patientQuery || !!data.dateFrom || !!data.dateTo || !!data.timeFrom || !!data.timeTo || !!data.branchId;
    let restrictIds: string[] | null = null;
    if (hasApptFilter) {
      let aq = context.supabase.from("appointments").select("id").limit(2000);
      if (data.branchId) aq = aq.eq("branch_id", data.branchId);
      if (data.dateFrom) aq = aq.gte("appointment_date", data.dateFrom);
      if (data.dateTo) aq = aq.lte("appointment_date", data.dateTo);
      if (data.timeFrom) aq = aq.gte("appointment_time", data.timeFrom);
      if (data.timeTo) aq = aq.lte("appointment_time", data.timeTo);
      if (data.patientQuery) {
        const esc = data.patientQuery.replace(/[%,()]/g, " ").trim();
        if (esc) aq = aq.or(`patient_name.ilike.%${esc}%,patient_phone.ilike.%${esc}%`);
      }
      const { data: matched, error: mErr } = await aq;
      if (mErr) throw new Error(mErr.message);
      restrictIds = (matched ?? []).map((r) => r.id);
      if (restrictIds.length === 0) return [];
    }

    let q = context.supabase
      .from("notifications")
      .select(
        "id, appointment_id, kind, audience, channel, send_status, title, body, created_at, sent_at, last_error, metadata",
      )
      .like("kind", "reminder_%")
      .order("created_at", { ascending: false })
      .limit(data.limit ?? 200);
    if (data.appointmentId) q = q.eq("appointment_id", data.appointmentId);
    if (data.channel) q = q.eq("channel", data.channel);
    if (data.audience) q = q.eq("audience", data.audience);
    if (data.status) q = q.eq("send_status", data.status);
    if (restrictIds) q = q.in("appointment_id", restrictIds);
    const { data: rows, error } = await q;
    if (error) throw new Error(error.message);

    const apptIds = Array.from(
      new Set((rows ?? []).map((r) => r.appointment_id).filter((v): v is string => !!v)),
    );
    const apptMap = new Map<string, ReminderDelivery["appointment"]>();
    if (apptIds.length > 0) {
      const { data: appts, error: aErr } = await context.supabase
        .from("appointments")
        .select("id, patient_name, patient_phone, appointment_date, appointment_time, status, branch_id")
        .in("id", apptIds);
      if (aErr) throw new Error(aErr.message);
      for (const a of appts ?? []) {
        apptMap.set(a.id, {
          id: a.id,
          patient_name: a.patient_name ?? null,
          patient_phone: a.patient_phone ?? null,
          appointment_date: a.appointment_date ?? null,
          appointment_time: a.appointment_time ?? null,
          status: (a.status as string | null) ?? null,
          branch_id: a.branch_id ?? null,
        });
      }
    }
    return (rows ?? []).map((r) => ({
      ...r,
      appointment: r.appointment_id ? apptMap.get(r.appointment_id) ?? null : null,
    })) as unknown as ReminderDelivery[];
  });

/* -------- Retry a failed / skipped reminder -------- */

export const retryReminderDelivery = createServerFn({ method: "POST" })
  .middleware([requireSupabaseAuth])
  .validator((d) => z.object({ id: z.string().uuid() }).parse(d))
  .handler(async ({ data, context }) => {
    const roles = await getRoles(context.supabase, context.userId);
    ensureStaff(roles);
    // Only allow retry on failed/skipped rows so pending/sent aren't clobbered
    const { data: row, error: rErr } = await context.supabase
      .from("notifications")
      .select("id, send_status, kind")
      .eq("id", data.id)
      .maybeSingle();
    if (rErr) throw new Error(rErr.message);
    if (!row) throw new Error("التذكير غير موجود.");
    if (!["failed", "skipped"].includes(row.send_status as string)) {
      throw new Error("لا يمكن إعادة إرسال هذا التذكير في حالته الحالية.");
    }
    const { error } = await context.supabase
      .from("notifications")
      .update({ send_status: "pending", last_error: null, sent_at: null } as never)
      .eq("id", data.id);
    if (error) throw new Error(error.message);
    return { ok: true };
  });

/* -------- Bulk retry failed/skipped reminders -------- */

export const retryReminderDeliveriesBulk = createServerFn({ method: "POST" })
  .middleware([requireSupabaseAuth])
  .validator((d) =>
    z.object({ ids: z.array(z.string().uuid()).min(1).max(200) }).parse(d),
  )
  .handler(async ({ data, context }) => {
    const roles = await getRoles(context.supabase, context.userId);
    ensureStaff(roles);
    const { data: rows, error: rErr } = await context.supabase
      .from("notifications")
      .select("id, send_status")
      .in("id", data.ids);
    if (rErr) throw new Error(rErr.message);
    const eligible = (rows ?? [])
      .filter((r) => ["failed", "skipped"].includes(r.send_status as string))
      .map((r) => r.id);
    if (eligible.length === 0) {
      return { ok: true, retried: 0, skipped: data.ids.length };
    }
    const { error } = await context.supabase
      .from("notifications")
      .update({ send_status: "pending", last_error: null, sent_at: null } as never)
      .in("id", eligible);
    if (error) throw new Error(error.message);
    await logAppEvent(context.supabase, "notifications.bulk_retry", {
      requested: data.ids.length,
      retried: eligible.length,
    });
    return { ok: true, retried: eligible.length, skipped: data.ids.length - eligible.length };
  });

/* -------- Export reminder deliveries as CSV -------- */

function csvEscape(v: unknown): string {
  if (v === null || v === undefined) return "";
  const s = String(v);
  if (/[",\n\r]/.test(s)) return `"${s.replace(/"/g, '""')}"`;
  return s;
}

export const exportReminderDeliveriesCsv = createServerFn({ method: "POST" })
  .middleware([requireSupabaseAuth])
  .validator((d: unknown) => ListRemindersInput.parse(d))
  .handler(async ({ data, context }) => {
    const roles = await getRoles(context.supabase, context.userId);
    ensureStaff(roles);

    // Reuse the same filter shape but bump the row cap for exports
    const hasApptFilter =
      !!data.patientQuery || !!data.dateFrom || !!data.dateTo || !!data.timeFrom || !!data.timeTo || !!data.branchId;
    let restrictIds: string[] | null = null;
    if (hasApptFilter) {
      let aq = context.supabase.from("appointments").select("id").limit(5000);
      if (data.branchId) aq = aq.eq("branch_id", data.branchId);
      if (data.dateFrom) aq = aq.gte("appointment_date", data.dateFrom);
      if (data.dateTo) aq = aq.lte("appointment_date", data.dateTo);
      if (data.timeFrom) aq = aq.gte("appointment_time", data.timeFrom);
      if (data.timeTo) aq = aq.lte("appointment_time", data.timeTo);
      if (data.patientQuery) {
        const esc = data.patientQuery.replace(/[%,()]/g, " ").trim();
        if (esc) aq = aq.or(`patient_name.ilike.%${esc}%,patient_phone.ilike.%${esc}%`);
      }
      const { data: matched, error: mErr } = await aq;
      if (mErr) throw new Error(mErr.message);
      restrictIds = (matched ?? []).map((r) => r.id);
      if (restrictIds.length === 0) {
        return { csv: "\uFEFFappointment_id,patient_name,patient_phone,appointment_date,appointment_time,kind,channel,audience,status,created_at,sent_at,last_error\n", count: 0, filename: buildFilename() };
      }
    }

    let q = context.supabase
      .from("notifications")
      .select(
        "id, appointment_id, kind, audience, channel, send_status, created_at, sent_at, last_error",
      )
      .like("kind", "reminder_%")
      .order("created_at", { ascending: false })
      .limit(5000);
    if (data.appointmentId) q = q.eq("appointment_id", data.appointmentId);
    if (data.channel) q = q.eq("channel", data.channel);
    if (data.audience) q = q.eq("audience", data.audience);
    if (data.status) q = q.eq("send_status", data.status);
    if (restrictIds) q = q.in("appointment_id", restrictIds);
    const { data: rows, error } = await q;
    if (error) throw new Error(error.message);

    const apptIds = Array.from(
      new Set((rows ?? []).map((r) => r.appointment_id).filter((v): v is string => !!v)),
    );
    const apptMap = new Map<string, { name: string | null; phone: string | null; date: string | null; time: string | null }>();
    if (apptIds.length > 0) {
      const { data: appts } = await context.supabase
        .from("appointments")
        .select("id, patient_name, patient_phone, appointment_date, appointment_time")
        .in("id", apptIds);
      for (const a of appts ?? []) {
        apptMap.set(a.id, {
          name: a.patient_name ?? null,
          phone: a.patient_phone ?? null,
          date: a.appointment_date ?? null,
          time: a.appointment_time ?? null,
        });
      }
    }

    const header =
      "appointment_id,patient_name,patient_phone,appointment_date,appointment_time,kind,channel,audience,status,created_at,sent_at,last_error";
    const lines = [header];
    for (const r of rows ?? []) {
      const a = r.appointment_id ? apptMap.get(r.appointment_id) : undefined;
      lines.push(
        [
          r.appointment_id ?? "",
          a?.name ?? "",
          a?.phone ?? "",
          a?.date ?? "",
          a?.time ?? "",
          r.kind,
          r.channel,
          r.audience,
          r.send_status,
          r.created_at,
          r.sent_at ?? "",
          r.last_error ?? "",
        ]
          .map(csvEscape)
          .join(","),
      );
    }
    // Prepend BOM so Excel opens Arabic content correctly
    const count = rows?.length ?? 0;
    await logAppEvent(context.supabase, "notifications.export_csv", {
      row_count: count,
      branch_id: data.branchId ?? null,
      from: data.dateFrom ?? null,
      to: data.dateTo ?? null,
      channel: data.channel ?? null,
      status: data.status ?? null,
    });
    return { csv: "\uFEFF" + lines.join("\n") + "\n", count, filename: buildFilename() };
  });

function buildFilename() {
  const d = new Date();
  const pad = (n: number) => String(n).padStart(2, "0");
  return `reminder-deliveries-${d.getFullYear()}${pad(d.getMonth() + 1)}${pad(d.getDate())}-${pad(d.getHours())}${pad(d.getMinutes())}.csv`;
}

/* -------- Delivery stats (success/failure by channel and time bucket) -------- */

export type DeliveryStats = {
  rangeMs: number;
  from: string;
  to: string;
  bucket: "hour" | "day";
  totals: { sent: number; failed: number; pending: number; skipped: number; queued: number };
  byChannel: Array<{
    channel: "in_app" | "web_push" | "sms" | "whatsapp" | "email";
    sent: number;
    failed: number;
    pending: number;
    skipped: number;
    queued: number;
  }>;
  byBucket: Array<{ label: string; sent: number; failed: number }>;
};

const CHANNELS = ["in_app", "web_push", "sms", "whatsapp", "email"] as const;

const MAX_RANGE_MS = 366 * 24 * 60 * 60 * 1000; // 1 year hard cap
const MIN_RANGE_MS = 5 * 60 * 1000; // 5 minutes min

const DeliveryStatsInput = z
  .object({
    // Preset in hours, OR custom from/to ISO datetime strings
    hours: z.number().int().min(1).max(366 * 24).optional(),
    from: z.string().datetime({ offset: true }).optional(),
    to: z.string().datetime({ offset: true }).optional(),
  })
  .default({})
  .refine(
    (v) => {
      // If either from or to is provided, both must be present
      if ((v.from && !v.to) || (v.to && !v.from)) return false;
      return true;
    },
    { message: "الرجاء تحديد بداية ونهاية الفترة معًا." },
  )
  .refine(
    (v) => {
      if (v.from && v.to) {
        const f = Date.parse(v.from);
        const t = Date.parse(v.to);
        if (!Number.isFinite(f) || !Number.isFinite(t)) return false;
        if (t <= f) return false;
        const range = t - f;
        if (range < MIN_RANGE_MS) return false;
        if (range > MAX_RANGE_MS) return false;
      }
      return true;
    },
    { message: "الفترة الزمنية غير صالحة (٥ دقائق حد أدنى، سنة واحدة حد أقصى، ويجب أن تسبق البداية النهاية)." },
  );

export const getReminderDeliveryStats = createServerFn({ method: "POST" })
  .middleware([requireSupabaseAuth])
  .validator((d: unknown) => DeliveryStatsInput.parse(d))
  .handler(async ({ data, context }): Promise<DeliveryStats> => {
    const roles = await getRoles(context.supabase, context.userId);
    ensureStaff(roles);

    const nowMs = Date.now();
    let toMs: number;
    let fromMs: number;
    if (data.from && data.to) {
      fromMs = Date.parse(data.from);
      toMs = Date.parse(data.to);
    } else {
      const hours = data.hours ?? 24 * 30; // default 30 days
      toMs = nowMs;
      fromMs = nowMs - hours * 60 * 60 * 1000;
    }
    const rangeMs = toMs - fromMs;
    const bucket: "hour" | "day" = rangeMs <= 48 * 60 * 60 * 1000 ? "hour" : "day";

    const { data: rows, error } = await context.supabase
      .from("notifications")
      .select("channel, send_status, created_at")
      .like("kind", "reminder_%")
      .gte("created_at", new Date(fromMs).toISOString())
      .lte("created_at", new Date(toMs).toISOString())
      .limit(20000);
    if (error) throw new Error(error.message);

    const totals = { sent: 0, failed: 0, pending: 0, skipped: 0, queued: 0 };
    const byChannelMap = new Map<
      string,
      { sent: number; failed: number; pending: number; skipped: number; queued: number }
    >();
    for (const c of CHANNELS)
      byChannelMap.set(c, { sent: 0, failed: 0, pending: 0, skipped: 0, queued: 0 });

    // Seed continuous buckets
    const bucketMap = new Map<string, { sent: number; failed: number }>();
    if (bucket === "hour") {
      const startHour = new Date(fromMs);
      startHour.setUTCMinutes(0, 0, 0);
      for (let t = startHour.getTime(); t <= toMs; t += 60 * 60 * 1000) {
        bucketMap.set(new Date(t).toISOString().slice(0, 13), { sent: 0, failed: 0 });
      }
    } else {
      const startDay = new Date(fromMs);
      startDay.setUTCHours(0, 0, 0, 0);
      for (let t = startDay.getTime(); t <= toMs; t += 24 * 60 * 60 * 1000) {
        bucketMap.set(new Date(t).toISOString().slice(0, 10), { sent: 0, failed: 0 });
      }
    }

    for (const r of rows ?? []) {
      const st = r.send_status as keyof typeof totals;
      if (st in totals) totals[st]++;
      const ch = byChannelMap.get(r.channel as string);
      if (ch && st in ch) (ch as any)[st]++;
      const key =
        bucket === "hour"
          ? String(r.created_at).slice(0, 13)
          : String(r.created_at).slice(0, 10);
      const b = bucketMap.get(key);
      if (b) {
        if (st === "sent") b.sent++;
        else if (st === "failed") b.failed++;
      }
    }

    const byChannel = CHANNELS.map((c) => ({ channel: c, ...(byChannelMap.get(c) as any) }));
    const byBucket = Array.from(bucketMap.entries())
      .sort(([a], [b]) => (a < b ? -1 : 1))
      .map(([label, v]) => ({ label, ...v }));

    return {
      rangeMs,
      from: new Date(fromMs).toISOString(),
      to: new Date(toMs).toISOString(),
      bucket,
      totals,
      byChannel,
      byBucket,
    };
  });


/* -------- Per-user notifications (bell) -------- */

const ListMyInput = z
  .object({
    limit: z.number().int().min(1).max(100).optional(),
    onlyUnread: z.boolean().optional(),
  })
  .default({});

export const listMyNotifications = createServerFn({ method: "POST" })
  .middleware([requireSupabaseAuth])
  .validator((d: unknown) => ListMyInput.parse(d))
  .handler(async ({ data, context }) => {
    const sb = context.supabase;
    const userId = context.userId;
    const roles = await getRoles(sb, userId);
    const isStaff = roles.some((r) =>
      (["admin", "super_admin", "reception", "doctor"] as Role[]).includes(r),
    );
    let q = sb
      .from("notifications")
      .select(
        "id, audience, kind, title, body, appointment_id, metadata, read_at, created_at",
      )
      .eq("channel", "in_app")
      .order("created_at", { ascending: false })
      .limit(data.limit ?? 30);
    q = isStaff
      ? q.or(`audience.eq.staff,user_id.eq.${userId}`)
      : q.eq("user_id", userId);
    if (data.onlyUnread) q = q.is("read_at", null);
    const { data: rows, error } = await q;
    if (error) throw new Error(error.message);
    return { items: rows ?? [] };
  });

export const countUnreadNotifications = createServerFn({ method: "GET" })
  .middleware([requireSupabaseAuth])
  .handler(async ({ context }) => {
    const sb = context.supabase;
    const userId = context.userId;
    const roles = await getRoles(sb, userId);
    const isStaff = roles.some((r) =>
      (["admin", "super_admin", "reception", "doctor"] as Role[]).includes(r),
    );
    let q = sb
      .from("notifications")
      .select("id", { count: "exact", head: true })
      .is("read_at", null)
      .eq("channel", "in_app");
    q = isStaff
      ? q.or(`audience.eq.staff,user_id.eq.${userId}`)
      : q.eq("user_id", userId);
    const { count, error } = await q;
    if (error) throw new Error(error.message);
    return { count: count ?? 0 };
  });

export const markNotificationsRead = createServerFn({ method: "POST" })
  .middleware([requireSupabaseAuth])
  .validator((d) =>
    z
      .object({
        id: z.string().uuid().optional(),
        all: z.boolean().optional(),
      })
      .refine((v) => v.id || v.all, "id or all required")
      .parse(d),
  )
  .handler(async ({ data, context }) => {
    const sb = context.supabase;
    const userId = context.userId;
    const roles = await getRoles(sb, userId);
    const isStaff = roles.some((r) =>
      (["admin", "super_admin", "reception", "doctor"] as Role[]).includes(r),
    );
    let q = sb.from("notifications").update({ read_at: new Date().toISOString() });
    if (data.id) q = q.eq("id", data.id);
    else q = q.is("read_at", null);
    q = isStaff
      ? q.or(`audience.eq.staff,user_id.eq.${userId}`)
      : q.eq("user_id", userId);
    const { error } = await q;
    if (error) throw new Error(error.message);
    return { ok: true };
  });
